/* Generated By:JJTree: Do not edit this line. ASTDeploymentDecl.java Version 6.0 */
package wyvern.tools.parsing.coreparser.arch.views.deployment;

public
class ASTDeploymentDecl extends SimpleNode {
  public ASTDeploymentDecl(int id) {
    super(id);
  }

  public ASTDeploymentDecl(DeploymentViewParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eccd30767ee06107538602b66d899b6e (do not edit this line) */
