/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 6.0 */
package wyvern.tools.parsing.coreparser.arch.views.deployment;

public
class ASTIdentifier extends SimpleNode {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(DeploymentViewParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8ce7f5707fbf0bbeea688f2af9420651 (do not edit this line) */
