/* Generated By:JJTree: Do not edit this line. ASTLhs.java Version 6.0 */
package wyvern.tools.parsing.coreparser.arch.views.deployment;

public
class ASTLhs extends SimpleNode {
  public ASTLhs(int id) {
    super(id);
  }

  public ASTLhs(DeploymentViewParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50e393d5f508cfd56af9303dc5e69aae (do not edit this line) */
