/* Generated By:JJTree: Do not edit this line. ASTLhsRemaining.java Version 6.0 */
package wyvern.tools.parsing.coreparser.arch.views.deployment;

public
class ASTLhsRemaining extends SimpleNode {
  public ASTLhsRemaining(int id) {
    super(id);
  }

  public ASTLhsRemaining(DeploymentViewParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c2b3b0d0a441d5c760d0e9e1f1669d84 (do not edit this line) */
