/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java Version 6.0 */
package wyvern.tools.parsing.coreparser.arch.views.deployment;

public
class ASTStringLiteral extends SimpleNode {
  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(DeploymentViewParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e2cc67bd6551d270dbddc7fca9bfbc31 (do not edit this line) */
