/* Generated By:JJTree: Do not edit this line. ASTSetter.java Version 6.0 */
package wyvern.tools.parsing.coreparser.arch.views.deployment;

public
class ASTSetter extends SimpleNode {
  public ASTSetter(int id) {
    super(id);
  }

  public ASTSetter(DeploymentViewParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b137e9e692b331645444d417e9b2ae50 (do not edit this line) */
