package wyvern.tools.errors;

import java.util.Optional;

public class WyvernException extends RuntimeException {
    /**
     * The serialization runtime associates with each serializable class a version number (serialVersionUID),
     * which is used during deserialization to verify that the sender and receiver of a serialized object
     * have loaded classes for that object that are compatible with respect to serialization.
     * This is an autogenerated version number.
     */
    private static final long serialVersionUID = -852763357402672869L;

    public WyvernException(String text) {
        super("Positionless error: " + text);
    }

    public WyvernException(String text, FileLocation location) {
        super("Wyvern has encountered the exception " + text + " at location " + location);
    }

    public WyvernException(String text, HasLocation location) {
        this(text, Optional.ofNullable(location).map(HasLocation::getLocation).orElse(null));
    }
}
