/* Generated By:JavaCC: Do not edit this line. ArchParserTreeConstants.java Version 5.0 */
package wyvern.tools.parsing.coreparser.arch;

public interface ArchParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTARCHTYPEDECLSEQ = 1;
  public int JJTCOMPONENTTYPEDECL = 2;
  public int JJTCONNECTORTYPEDECL = 3;
  public int JJTARCHITECTURETYPEDECL = 4;
  public int JJTARCHELEMDECLSEQ = 5;
  public int JJTCOMPONENTDECLS = 6;
  public int JJTCONNECTORDECLS = 7;
  public int JJTATTACHMENTDECLS = 8;
  public int JJTBINDINGDECLS = 9;
  public int JJTENTRYPOINTDECLS = 10;
  public int JJTPORTDECL = 11;
  public int JJTVALDECL = 12;


  public String[] jjtNodeName = {
    "void",
    "ArchTypeDeclSeq",
    "ComponentTypeDecl",
    "ConnectorTypeDecl",
    "ArchitectureTypeDecl",
    "ArchElemDeclSeq",
    "ComponentDecls",
    "ConnectorDecls",
    "AttachmentDecls",
    "BindingDecls",
    "EntryPointDecls",
    "PortDecl",
    "ValDecl",
  };
}
/* JavaCC - OriginalChecksum=0d779f437f22f2f559c66b730825ed31 (do not edit this line) */
