/* Generated By:JavaCC: Do not edit this line. ArchParserVisitor.java Version 5.0 */
package wyvern.tools.parsing.coreparser.arch;

public interface ArchParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTArchDesc node, Object data);
  public Object visit(ASTComponentTypeDecl node, Object data);
  public Object visit(ASTConnectorTypeDecl node, Object data);
  public Object visit(ASTArchitectureTypeDecl node, Object data);
  public Object visit(ASTComponentDecls node, Object data);
  public Object visit(ASTConnectorDecls node, Object data);
  public Object visit(ASTAttachmentDecls node, Object data);
  public Object visit(ASTBindingDecls node, Object data);
  public Object visit(ASTEntryPointDecls node, Object data);
  public Object visit(ASTPortDecl node, Object data);
  public Object visit(ASTValDecl node, Object data);
}
/* JavaCC - OriginalChecksum=a5490dbb3d8cb8cd0196a8c7121cb319 (do not edit this line) */
