/* Generated By:JavaCC: Do not edit this line. ArchParserVisitor.java Version 5.0 */
package wyvern.tools.parsing.coreparser.arch;

public interface ArchParserVisitor {
    Object visit(SimpleNode node, Object data);

    Object visit(ASTArchDesc node, Object data);

    Object visit(ASTComponentTypeDecl node, Object data);

    Object visit(ASTConnectorTypeDecl node, Object data);

    Object visit(ASTArchitectureTypeDecl node, Object data);

    Object visit(ASTComponentDecl node, Object data);

    Object visit(ASTConnectorDecl node, Object data);

    Object visit(ASTAttachmentDecl node, Object data);

    Object visit(ASTBindingDecl node, Object data);

    Object visit(ASTEntryPointDecl node, Object data);

    Object visit(ASTPortDecl node, Object data);

    Object visit(ASTValDecl node, Object data);
}
/* JavaCC - OriginalChecksum=d1ed00e694c4f9cc2e7a09c1da530eb6 (do not edit this line) */
