/* Generated By:JavaCC: Do not edit this line. ArchParserTreeConstants.java Version 5.0 */
package wyvern.tools.parsing.coreparser.arch;

public interface ArchParserTreeConstants
{
  public int JJTARCHDESC = 0;
  public int JJTVOID = 1;
  public int JJTCOMPONENTTYPEDECL = 2;
  public int JJTCONNECTORTYPEDECL = 3;
  public int JJTARCHITECTURETYPEDECL = 4;
  public int JJTCOMPONENTDECLS = 5;
  public int JJTCONNECTORDECLS = 6;
  public int JJTATTACHMENTDECLS = 7;
  public int JJTBINDINGDECLS = 8;
  public int JJTENTRYPOINTDECLS = 9;
  public int JJTPORTDECL = 10;
  public int JJTVALDECL = 11;


  public String[] jjtNodeName = {
    "ArchDesc",
    "void",
    "ComponentTypeDecl",
    "ConnectorTypeDecl",
    "ArchitectureTypeDecl",
    "ComponentDecls",
    "ConnectorDecls",
    "AttachmentDecls",
    "BindingDecls",
    "EntryPointDecls",
    "PortDecl",
    "ValDecl",
  };
}
/* JavaCC - OriginalChecksum=ebf8723db09d5e2f750ef113c9b642a0 (do not edit this line) */
