/* Generated By:JJTree: Do not edit this line. ASTArchTypeDeclSeq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wyvern.tools.parsing.coreparser.arch;

public
class ASTArchTypeDeclSeq extends SimpleNode {
  public ASTArchTypeDeclSeq(int id) {
    super(id);
  }

  public ASTArchTypeDeclSeq(ArchParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArchParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d7c7addb6d57679f30b1ab664ee6b348 (do not edit this line) */
