/* Generated By:JJTree: Do not edit this line. ASTAttachmentDecls.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wyvern.tools.parsing.coreparser.arch;

public
class ASTAttachmentDecls extends SimpleNode {
  public ASTAttachmentDecls(int id) {
    super(id);
  }

  public ASTAttachmentDecls(ArchParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArchParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f589db3b113ce286cccdd76bc5f0956 (do not edit this line) */
