/* Generated By:JJTree: Do not edit this line. ASTArchitectureTypeDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wyvern.tools.parsing.coreparser.arch;

public
class ASTArchitectureTypeDecl extends SimpleNode {
  public ASTArchitectureTypeDecl(int id) {
    super(id);
  }

  public ASTArchitectureTypeDecl(ArchParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArchParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a58adf2dc7bb6ca5c58bdcc7b1dacfa1 (do not edit this line) */
