/* Generated By:JJTree: Do not edit this line. ASTComponentTypeDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wyvern.tools.parsing.coreparser.arch;

public
class ASTComponentTypeDecl extends SimpleNode {
  public ASTComponentTypeDecl(int id) {
    super(id);
  }

  public ASTComponentTypeDecl(ArchParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArchParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f5aec0da9432112df1e15710b91b7b28 (do not edit this line) */
