/* Generated By:JJTree: Do not edit this line. ASTConnectorTypeDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wyvern.tools.parsing.coreparser.arch;

public
class ASTConnectorTypeDecl extends SimpleNode {
  public ASTConnectorTypeDecl(int id) {
    super(id);
  }

  public ASTConnectorTypeDecl(ArchParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArchParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=884a938c5fd0ec5939d4c5c7e8dc6912 (do not edit this line) */
