/* Generated By:JJTree: Do not edit this line. ASTEntryPointDecls.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wyvern.tools.parsing.coreparser.arch;

public
class ASTEntryPointDecls extends SimpleNode {
  public ASTEntryPointDecls(int id) {
    super(id);
  }

  public ASTEntryPointDecls(ArchParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArchParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c8b2a83909a3e037766bd7aca4771d95 (do not edit this line) */
