/* Generated By:JJTree: Do not edit this line. ASTPortDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,
NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wyvern.tools.parsing.coreparser.arch;

public class ASTPortDecl extends SimpleNode {
    // "port" is the name of the port declared
    private String port;
    // "requires" is the name of the interface required by the port,
    // or empty string if the port doesn't require any interface
    private String requires;
    // "provides" is the name of the interface provided by the port,
    // or empty string if the port doesn't provide any interface
    private String provides;

    public ASTPortDecl(int id) {
        super(id);
        requires = "";
        provides = "";
    }

    public ASTPortDecl(ArchParser p, int id) {
        super(p, id);
    }

    public void setRequires(String r) {
        requires = r;
    }

    public String getRequires() {
        return requires;
    }

    public void setProvides(String r) {
        provides = r;
    }

    public String getProvides() {
        return provides;
    }

    public void setPort(String p) {
        port = p;
    }

    public String getPort() {
        return port;
    }

    public String toString() {
        return "port " + port;
    }

    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(ArchParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/*
 * JavaCC - OriginalChecksum=8103444d4a579c37283fc481f4a3775b (do not edit this
 * line)
 */
