/* Generated By:JavaCC: Do not edit this line. ArchParserConstants.java */
package wyvern.tools.parsing.coreparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ArchParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMPONENT = 1;
  /** RegularExpression Id. */
  int EXTERNAL = 2;
  /** RegularExpression Id. */
  int PORT = 3;
  /** RegularExpression Id. */
  int PROVIDES = 4;
  /** RegularExpression Id. */
  int REQUIRES = 5;
  /** RegularExpression Id. */
  int TARGET = 6;
  /** RegularExpression Id. */
  int CONNECTOR = 7;
  /** RegularExpression Id. */
  int VAL = 8;
  /** RegularExpression Id. */
  int ARCHITECTURE = 9;
  /** RegularExpression Id. */
  int COMPONENTS = 10;
  /** RegularExpression Id. */
  int CONNECTORS = 11;
  /** RegularExpression Id. */
  int ATTACHMENTS = 12;
  /** RegularExpression Id. */
  int CONNECT = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int WITH = 15;
  /** RegularExpression Id. */
  int ENTRYPOINTS = 16;
  /** RegularExpression Id. */
  int BINDINGS = 17;
  /** RegularExpression Id. */
  int IS = 18;
  /** RegularExpression Id. */
  int COLON = 19;
  /** RegularExpression Id. */
  int DOT = 20;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 21;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 22;
  /** RegularExpression Id. */
  int WHITESPACE = 23;
  /** RegularExpression Id. */
  int DEDENT = 24;
  /** RegularExpression Id. */
  int INDENT = 25;
  /** RegularExpression Id. */
  int NEWLINE = 26;
  /** RegularExpression Id. */
  int IDENTIFIER = 27;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<WHITESPACE>",
    "\"component\"",
    "\"external\"",
    "\"port\"",
    "\"provides\"",
    "\"requires\"",
    "\"target\"",
    "\"connector\"",
    "\"val\"",
    "\"architecture\"",
    "\"components\"",
    "\"connectors\"",
    "\"attachments\"",
    "\"connect\"",
    "\"and\"",
    "\"with\"",
    "\"entryPoints\"",
    "\"bindings\"",
    "\"is\"",
    "<DEDENT>",
    "<INDENT>",
    "<NEWLINE>",
    "<IDENTIFIER>",
    "\":\"",
    "\".\"",
  };

}
